# This workflow runs our benchmarks uploads the results to S3 and sends a notification to
# slack when it's done.
name: Benchmark

on:
  schedule:
    - cron: '0 14 * * *'  # Runs at 6 am PST
  workflow_dispatch:

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install .
          pip install -r dev-requirements.txt

      - name: Run and upload benchmarks
        run: ./scripts/run_and_upload_benchmarks.sh
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: 'us-east-2'
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            SLACK_BENCHMARK_NOTIFICATION_WEBHOOK: ${{ secrets.SLACK_BENCHMARK_NOTIFICATION_WEBHOOK }}
